name: zCrono
version: '1.0.0'
main: com.zKraft.zCrono
api-version: '1.21'
commands:
  parkour:
    description: Gestisce le mappe parkour
    usage: /parkour
    permission: zcrono.admin
permissions:
  zcrono.admin:
    description: Consente di configurare le mappe parkour
    default: op
