name: zCrono
version: '${version}'
main: com.zKraft.zCrono
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  zcrono:
    description: Gestisce le mappe configurate per zCrono
    usage: /zcrono
permissions:
  zcrono.admin:
    description: Consente di configurare le mappe di zCrono
    default: op
